export const STRINGS = {
  pt: {
    welcome: 'Bem-vindo de volta',
    instruction: 'Continue sua jornada de aprendizado',
    loginPlaceholder: 'Login',
    passwordPlaceholder: 'Senha',
    remember: 'Lembrar de mim',
    submit: 'Entrar',
    footer: '© 2025 Singular. Todos os direitos reservados.',
  },
  en: {
    welcome: 'Welcome back',
    instruction: 'Continue your learning journey',
    loginPlaceholder: 'Login',
    passwordPlaceholder: 'Password',
    remember: 'Remember me',
    submit: 'Sign in',
    footer: '© 2025 Singular. All rights reserved.',
  },
};

export const USERS = [
  { id: 'caio-marques', name: 'Caio Marques', initials: 'CM', avatarBg: '#2a8c97' },
  { id: 'gabriel-alves', name: 'Gabriel Alves', initials: 'GA', avatarBg: '#4fd1de' },
  { id: 'caio-araujo', name: 'Caio Araújo', initials: 'CA', avatarBg: '#7a5b1e' },
  { id: 'henrique-gomes', name: 'Henrique Gomes', initials: 'HG', avatarBg: '#0a4a52' },
];

export const STATUS_DEFS = [
  { id: 'backlog', color: '#64748b' },
  { id: 'dev', color: '#3b82f6' },
  { id: 'testing', color: '#a855f7' },
  { id: 'pendInt', color: '#f59e0b' },
  { id: 'pendExt', color: '#f97316' },
  { id: 'cancelled', color: '#ef4444' },
  { id: 'commit', color: '#22c55e' },
];

export const TASKS_SEED = [
  { id: 't1', userId: 'caio-marques', titulo: 'Revisar contrato Premium Office Q3', projeto: 'Premium Office', tarefa: 'Revisão Contratual', detalhes: 'Revisar cláusulas de renovação do contrato Premium Office antes do vencimento em setembro.', criadoEm: '02/08/2026', prazo: '20/09/2026', status: 'backlog', concluida: false },
  { id: 't2', userId: 'caio-marques', titulo: 'Auditar caso Blindagem Financeira #482', projeto: 'Blindagem Financeira', tarefa: 'Andamento Processual', detalhes: 'Acompanhar petição do processo #482 e atualizar o cliente sobre o andamento.', criadoEm: '10/08/2026', prazo: '25/09/2026', status: 'pendExt', concluida: false },
  { id: 't3', userId: 'caio-marques', titulo: 'Configurar pipeline de Automação de faturas', projeto: 'Automação', tarefa: 'Desenvolvimento', detalhes: 'Construir pipeline que automatiza a emissão e o envio de faturas mensais.', criadoEm: '14/08/2026', prazo: null, status: 'dev', concluida: false },
  { id: 't4', userId: 'caio-marques', titulo: 'Validar módulo financeiro DAP Faculty', projeto: 'DAP Faculty', tarefa: 'Testes', detalhes: 'Validar cálculo de mensalidades no módulo financeiro antes da liberação aos alunos.', criadoEm: '01/08/2026', prazo: '18/09/2026', status: 'testing', concluida: false },
  { id: 't5', userId: 'caio-marques', titulo: 'Publicar relatório mensal Business Inteligence', projeto: 'Business Inteligence', tarefa: 'Relatório', detalhes: 'Consolidar indicadores do mês e publicar o relatório para a diretoria.', criadoEm: '28/07/2026', prazo: '30/08/2026', status: 'commit', concluida: true },
  { id: 't6', userId: 'gabriel-alves', titulo: 'Mapear fluxo de onboarding DapZap', projeto: 'DapZap', tarefa: 'Onboarding', detalhes: 'Desenhar o fluxo de boas-vindas para novos clientes do DapZap Bot.', criadoEm: '05/08/2026', prazo: null, status: 'backlog', concluida: false },
  { id: 't7', userId: 'gabriel-alves', titulo: 'Corrigir bug de envio no DapZap Bot', projeto: 'DapZap', tarefa: 'Suporte ao Cliente', detalhes: 'Investigar falha no envio de mensagens relatada por clientes do plano Pro.', criadoEm: '12/08/2026', prazo: '15/09/2026', status: 'dev', concluida: false },
  { id: 't8', userId: 'gabriel-alves', titulo: 'Migrar base do plano Free', projeto: 'Free', tarefa: 'Desenvolvimento', detalhes: 'Migrar contas do plano Free para a nova infraestrutura de banco de dados.', criadoEm: '16/08/2026', prazo: '30/09/2026', status: 'dev', concluida: false },
  { id: 't9', userId: 'gabriel-alves', titulo: 'Revisar processo Blindagem Financeira #510', projeto: 'Blindagem Financeira', tarefa: 'Andamento Processual', detalhes: 'Revisar documentação do processo #510 antes da audiência marcada.', criadoEm: '03/08/2026', prazo: '10/09/2026', status: 'pendInt', concluida: false },
  { id: 't10', userId: 'gabriel-alves', titulo: 'Encerrar sprint Automação RH', projeto: 'Automação', tarefa: 'Reunião Estratégica', detalhes: 'Encerrar sprint com o time de RH e alinhar próximos automatismos.', criadoEm: '30/07/2026', prazo: '25/08/2026', status: 'commit', concluida: true },
  { id: 't11', userId: 'caio-araujo', titulo: 'Levantar requisitos Premium Office Enterprise', projeto: 'Premium Office', tarefa: 'Levantamento', detalhes: 'Levantar requisitos para o novo plano Enterprise do Premium Office.', criadoEm: '08/08/2026', prazo: '01/10/2026', status: 'backlog', concluida: false },
  { id: 't12', userId: 'caio-araujo', titulo: 'Auditar contratos DAP Faculty turma 2026', projeto: 'DAP Faculty', tarefa: 'Revisão Contratual', detalhes: 'Auditar contratos da turma 2026 antes do início das aulas.', criadoEm: '11/08/2026', prazo: null, status: 'pendInt', concluida: false },
  { id: 't13', userId: 'caio-araujo', titulo: 'Ajustar dashboard Business Inteligence', projeto: 'Business Inteligence', tarefa: 'Desenvolvimento', detalhes: 'Ajustar filtros e gráficos do dashboard executivo de Business Inteligence.', criadoEm: '15/08/2026', prazo: '22/09/2026', status: 'dev', concluida: false },
  { id: 't14', userId: 'caio-araujo', titulo: 'Homologar automação de cobrança', projeto: 'Automação', tarefa: 'Testes', detalhes: 'Homologar fluxo de cobrança automática antes de liberar para produção.', criadoEm: '06/08/2026', prazo: '12/09/2026', status: 'testing', concluida: false },
  { id: 't15', userId: 'caio-araujo', titulo: 'Fechar caso Blindagem Financeira #399', projeto: 'Blindagem Financeira', tarefa: 'Andamento Processual', detalhes: 'Encerrar processo #399 após confirmação de pagamento do cliente.', criadoEm: '25/07/2026', prazo: '20/08/2026', status: 'commit', concluida: true },
  { id: 't16', userId: 'henrique-gomes', titulo: 'Planejar campanha plano Free', projeto: 'Free', tarefa: 'Marketing', detalhes: 'Planejar campanha de conversão do plano Free para o plano Pro.', criadoEm: '09/08/2026', prazo: null, status: 'cancelled', concluida: false },
  { id: 't17', userId: 'henrique-gomes', titulo: 'Configurar integração DapZap x CRM', projeto: 'DapZap', tarefa: 'Integração', detalhes: 'Configurar integração entre o DapZap e o CRM da equipe comercial.', criadoEm: '13/08/2026', prazo: '28/09/2026', status: 'dev', concluida: false },
  { id: 't18', userId: 'henrique-gomes', titulo: 'Atender chamado Premium Office VIP', projeto: 'Premium Office', tarefa: 'Suporte ao Cliente', detalhes: 'Atender chamado prioritário de cliente VIP do Premium Office.', criadoEm: '17/08/2026', prazo: '05/09/2026', status: 'pendExt', concluida: false },
  { id: 't19', userId: 'henrique-gomes', titulo: 'Revisar apostila DAP Faculty módulo 3', projeto: 'DAP Faculty', tarefa: 'Revisão de Conteúdo', detalhes: 'Revisar apostila do módulo 3 antes da publicação para os alunos.', criadoEm: '04/08/2026', prazo: '08/09/2026', status: 'testing', concluida: false },
  { id: 't20', userId: 'henrique-gomes', titulo: 'Consolidar métricas Business Inteligence', projeto: 'Business Inteligence', tarefa: 'Relatório', detalhes: 'Consolidar métricas trimestrais para apresentação de Business Inteligence.', criadoEm: '27/07/2026', prazo: '15/08/2026', status: 'commit', concluida: true },
];

export function extractYouTubeId(url) {
  if (!url) return '';
  const m = url.match(/(?:youtu\.be\/|[?&]v=|\/embed\/)([A-Za-z0-9_-]{11})/);
  return m ? m[1] : '';
}

export const SONGS_SEED = [
  { id: 's1', titulo: 'Faixa de exemplo 1', link: 'https://www.youtube.com/watch?v=oiZCY97dLhw', videoId: 'oiZCY97dLhw', addedBy: 'Caio Marques' },
  { id: 's2', titulo: 'Faixa de exemplo 2', link: 'https://www.youtube.com/watch?v=4zJF-pGRHQE', videoId: '4zJF-pGRHQE', addedBy: 'Gabriel Alves' },
];

export const PLAYLISTS_SEED = [
  { id: 'p1', nome: 'Favoritas', songIds: ['s1', 's2'] },
];

export const APP_STRINGS = {
  pt: {
    navHomeLabel: 'Início',
    navInternalChat: 'Chat Interno',
    navLabel: 'Equipe',
    viewKanban: 'Kanban',
    viewTable: 'Tabela',
    colTitulo: 'Título', colProjeto: 'Projeto', colTarefa: 'Tarefa', colDetalhes: 'Detalhes', colCriadoEm: 'Criado em', colPrazo: 'Prazo', colStatus: 'Status', colAcoes: 'Ações',
    verDetalhes: 'Ver detalhes',
    inexistente: 'Inexistente',
    tasksAssigned: 'tarefas atribuídas',
    detailsLabel: 'Detalhes e especificações',
    searchPlaceholder: 'Buscar em título, projeto, tarefa, detalhes…',
    allProjects: 'Todos os projetos',
    statusLabels: { backlog: 'Backlog', dev: 'Em Desenvolvimento', testing: 'Para Testes', pendInt: 'Pendência Interna', pendExt: 'Pendência Externa', cancelled: 'Cancelado', commit: 'Para Commit' },
    fieldTitulo: 'Título', fieldPrazo: 'Prazo', fieldStatus: 'Status', fieldResponsavel: 'Responsável',
    actionModalTitle: 'Editar tarefa',
    prazoPlaceholder: 'Sem prazo definido',
    deleteLabel: 'Excluir tarefa', cancelLabel: 'Cancelar', saveLabel: 'Salvar alterações',
    updateToastTitle: 'Tarefa atualizada', updateToastMsg: 'As alterações foram salvas.',
    deleteToastTitle: 'Tarefa excluída', deleteToastMsg: 'A tarefa foi removida do quadro.',
    settingsLabel: 'Configurações', logoutLabel: 'Sair',
    settingsTitle: 'Configurações', settingsLanguage: 'Idioma', settingsNotifications: 'Notificações',
    logoutTitle: 'Sair da conta', logoutBody: 'Tem certeza que deseja sair? Seus dados salvos localmente serão limpos neste dispositivo.',
    logoutCancel: 'Cancelar', logoutConfirm: 'Sair',
    playerUnavailableNote: 'Player de áudio/vídeo indisponível neste preview.',
    completedLabel: 'Tarefa concluída', reactivateLabel: 'Reativar tarefa',
    reactivateToastTitle: 'Tarefa reativada', reactivateToastMsg: 'A tarefa voltou para o quadro ativo.',
    redirectButton: 'Redirecionamento', redirectTitle: 'Redirecionamento',
    redirectSearchPlaceholder: 'Buscar por música ou quem adicionou…',
    addLabel: '+ Adicionar', songTitlePlaceholder: 'Título da música', songLinkPlaceholder: 'Link do YouTube',
    songAddedByPlaceholder: 'Quem adicionou', saveSongLabel: 'Salvar música',
    prevPage: 'Anterior', nextPage: 'Próxima',
    playlistTitle: 'Escolher playlist', newPlaylistLabel: 'Nova playlist', playlistNamePlaceholder: 'Nome da playlist',
    createPlaylistLabel: 'Criar playlist', noSongLabel: 'Nenhuma música selecionada',
    whatsappConnect: 'Conectar Chat',
    whatsappConnecting: 'Conectando...',
    whatsappConnected: 'Chat Conectado',
    whatsappOpen: 'Abrir',
    whatsappDisconnect: 'Desconectar',
    whatsappQrTitle: 'Conectar Chat',
    whatsappQrInstruction: 'Abra o aplicativo de mensagens no celular > Dispositivos conectados > Conectar e aponte a câmera para esta tela.',
    whatsappQrSimulate: 'Simular Conexão',
    whatsappServerLabel: 'Servidor:',
    whatsappWebTitle: 'Chat / Mensagens',
    whatsappSearchPlaceholder: 'Pesquisar mensagens',
    whatsappTypeMessage: 'Digite uma mensagem...',
    whatsappOnline: 'online',
    whatsappTyping: 'digitando...',
    whatsappSimulateReply: 'Simular Resposta',
  },
  en: {
    navHomeLabel: 'Home',
    navInternalChat: 'Internal Chat',
    navLabel: 'Team',
    viewKanban: 'Kanban',
    viewTable: 'Table',
    colTitulo: 'Title', colProjeto: 'Project', colTarefa: 'Task', colDetalhes: 'Details', colCriadoEm: 'Created', colPrazo: 'Due', colStatus: 'Status', colAcoes: 'Actions',
    verDetalhes: 'View details',
    inexistente: 'None',
    tasksAssigned: 'tasks assigned',
    detailsLabel: 'Details and specifications',
    searchPlaceholder: 'Search title, project, task, details…',
    allProjects: 'All projects',
    statusLabels: { backlog: 'Backlog', dev: 'In Development', testing: 'For Testing', pendInt: 'Internal Blocker', pendExt: 'External Blocker', cancelled: 'Cancelled', commit: 'Ready to Commit' },
    fieldTitulo: 'Title', fieldPrazo: 'Due date', fieldStatus: 'Status', fieldResponsavel: 'Assignee',
    actionModalTitle: 'Edit task',
    prazoPlaceholder: 'No due date',
    deleteLabel: 'Delete task', cancelLabel: 'Cancel', saveLabel: 'Save changes',
    updateToastTitle: 'Task updated', updateToastMsg: 'Your changes were saved.',
    deleteToastTitle: 'Task deleted', deleteToastMsg: 'The task was removed from the board.',
    settingsLabel: 'Settings', logoutLabel: 'Log out',
    settingsTitle: 'Settings', settingsLanguage: 'Language', settingsNotifications: 'Notifications',
    logoutTitle: 'Log out', logoutBody: 'Are you sure you want to log out? Locally saved data will be cleared on this device.',
    logoutCancel: 'Cancel', logoutConfirm: 'Log out',
    playerUnavailableNote: 'Audio/video player unavailable in this preview.',
    completedLabel: 'Task completed', reactivateLabel: 'Reactivate task',
    reactivateToastTitle: 'Task reactivated', reactivateToastMsg: 'The task is back on the active board.',
    redirectButton: 'Redirect', redirectTitle: 'Redirect',
    redirectSearchPlaceholder: 'Search by song or who added it…',
    addLabel: '+ Add', songTitlePlaceholder: 'Song title', songLinkPlaceholder: 'YouTube link',
    songAddedByPlaceholder: 'Added by', saveSongLabel: 'Save song',
    prevPage: 'Previous', nextPage: 'Next',
    playlistTitle: 'Choose playlist', newPlaylistLabel: 'New playlist', playlistNamePlaceholder: 'Playlist name',
    createPlaylistLabel: 'Create playlist', noSongLabel: 'No song selected',
    whatsappConnect: 'Connect Chat',
    whatsappConnecting: 'Connecting...',
    whatsappConnected: 'Chat Connected',
    whatsappOpen: 'Open',
    whatsappDisconnect: 'Disconnect',
    whatsappQrTitle: 'Connect Chat',
    whatsappQrInstruction: 'Open the messaging app on your phone > Linked Devices > Link a Device and point your phone to this screen.',
    whatsappQrSimulate: 'Simulate Connection',
    whatsappServerLabel: 'Server:',
    whatsappWebTitle: 'Chat / Messages',
    whatsappSearchPlaceholder: 'Search messages',
    whatsappTypeMessage: 'Type a message...',
    whatsappOnline: 'online',
    whatsappTyping: 'typing...',
    whatsappSimulateReply: 'Simulate Reply',
  },
};

export const WHATSAPP_CHATS_SEED = [
  {
    id: 'c1',
    name: 'Gabriel Alves',
    phone: '+55 11 98765-4321',
    avatar: 'GA',
    avatarBg: '#2a8c97',
    unread: 2,
    online: true,
    lastSeen: 'online',
    messages: [
      { id: 'm1', text: 'Oi Caio! Conseguiu revisar os prazos da sprint no Singular Scrum?', sender: 'contact', timestamp: '16:45', status: 'read' },
      { id: 'm2', text: 'Sim, Gabriel! Acabei de atualizar o quadro Kanban com as novas entregas.', sender: 'me', timestamp: '16:47', status: 'read' },
      { id: 'm3', text: 'Excelente! Vamos alinhar o deploy com o time de testes e fechar a release.', sender: 'contact', timestamp: '17:02', status: 'read' },
      { id: 'm4', text: 'Já mandei os links do repositório no canal.', sender: 'contact', timestamp: '17:04', status: 'received' },
    ],
  },
  {
    id: 'c2',
    name: 'Caio Araújo',
    phone: '+55 11 91234-5678',
    avatar: 'CA',
    avatarBg: '#8c6e2a',
    unread: 0,
    online: false,
    lastSeen: 'visto por último hoje às 16:30',
    messages: [
      { id: 'm21', text: 'Fala Caio, terminei a documentação da API e as rotas do Bitrix24.', sender: 'contact', timestamp: '14:20', status: 'read' },
      { id: 'm22', text: 'Perfeito! Ficou muito claro o fluxo de autenticação e Webhooks.', sender: 'me', timestamp: '14:25', status: 'read' },
    ],
  },
  {
    id: 'c3',
    name: 'Henrique Gomes',
    phone: '+55 11 99887-6655',
    avatar: 'HG',
    avatarBg: '#1e5f6e',
    unread: 0,
    online: true,
    lastSeen: 'online',
    messages: [
      { id: 'm31', text: 'Ajustei os testes unitários do backend, subindo no git agora.', sender: 'contact', timestamp: '15:10', status: 'read' },
      { id: 'm32', text: 'Valeu Henrique! Aprovado no code review.', sender: 'me', timestamp: '15:18', status: 'read' },
    ],
  },
  {
    id: 'c4',
    name: 'Grupo Singular Devs 🚀',
    phone: 'Grupo • 4 participantes',
    avatar: 'SD',
    avatarBg: '#075E54',
    isGroup: true,
    unread: 1,
    online: true,
    lastSeen: 'Gabriel, Caio A., Henrique e você',
    messages: [
      { id: 'm41', text: 'Reunião de alinhamento diário às 10h amanhã!', sender: 'contact', author: 'Gabriel Alves', timestamp: '11:00', status: 'read' },
      { id: 'm42', text: 'Confirmado pessoal, vou apresentar os novos cards do Scrum.', sender: 'me', timestamp: '11:05', status: 'read' },
      { id: 'm43', text: 'Show de bola, nos vemos amanhã!', sender: 'contact', author: 'Caio Araújo', timestamp: '16:50', status: 'received' },
    ],
  },
];

export const THEMES = {
  dark: {
    bg: '#050f13', text: '#ffffff', muted: 'rgba(255,255,255,0.75)', cardBg: 'rgba(255,255,255,0.05)', cardBorder: 'rgba(255,255,255,0.08)', track: 'rgba(255,255,255,0.1)', accent: '#4fd1de',
    toolbarBg: 'rgba(255,255,255,0.05)', toolbarBorder: 'rgba(255,255,255,0.1)', toolbarBtnBg: 'rgba(255,255,255,0.08)', toolbarIcon: '#ffffff',
    pageBg: '#050f13',
    surfaceBg: 'rgba(6,20,25,0.96)', surfaceBorder: 'rgba(255,255,255,0.08)',
    surfaceText: '#ffffff', surfaceMuted: 'rgba(255,255,255,0.45)', surfaceSubtle: 'rgba(255,255,255,0.6)',
    modalBg: '#0a1f24', modalBorder: 'rgba(255,255,255,0.1)',
    inputBg: 'rgba(255,255,255,0.06)', inputBorder: 'rgba(255,255,255,0.12)',
    hoverBg: 'rgba(255,255,255,0.08)', overlayBg: 'rgba(0,0,0,0.6)',
  },
  porcelain: {
    bg: '#faf9f6', text: '#171717', muted: 'rgba(0,0,0,0.6)', cardBg: 'rgba(0,0,0,0.04)', cardBorder: 'rgba(0,0,0,0.1)', track: 'rgba(0,0,0,0.1)', accent: '#0a6b74',
    toolbarBg: 'rgba(0,0,0,0.04)', toolbarBorder: 'rgba(0,0,0,0.1)', toolbarBtnBg: 'rgba(0,0,0,0.06)', toolbarIcon: '#171717',
    pageBg: '#faf9f6',
    surfaceBg: 'rgba(255,255,255,0.92)', surfaceBorder: 'rgba(0,0,0,0.1)',
    surfaceText: '#171717', surfaceMuted: 'rgba(0,0,0,0.45)', surfaceSubtle: 'rgba(0,0,0,0.6)',
    modalBg: '#ffffff', modalBorder: 'rgba(0,0,0,0.1)',
    inputBg: 'rgba(0,0,0,0.04)', inputBorder: 'rgba(0,0,0,0.12)',
    hoverBg: 'rgba(0,0,0,0.06)', overlayBg: 'rgba(0,0,0,0.4)',
  },
  sepia: {
    bg: '#f5ecd7', text: '#2b2410', muted: 'rgba(30,20,5,0.65)', cardBg: 'rgba(0,0,0,0.04)', cardBorder: 'rgba(0,0,0,0.1)', track: 'rgba(0,0,0,0.12)', accent: '#7a5b1e',
    toolbarBg: 'rgba(0,0,0,0.04)', toolbarBorder: 'rgba(0,0,0,0.1)', toolbarBtnBg: 'rgba(0,0,0,0.06)', toolbarIcon: '#2b2410',
    pageBg: '#f5ecd7',
    surfaceBg: 'rgba(245,236,215,0.95)', surfaceBorder: 'rgba(0,0,0,0.1)',
    surfaceText: '#2b2410', surfaceMuted: 'rgba(30,20,5,0.5)', surfaceSubtle: 'rgba(30,20,5,0.65)',
    modalBg: '#fbf5e8', modalBorder: 'rgba(0,0,0,0.1)',
    inputBg: 'rgba(0,0,0,0.05)', inputBorder: 'rgba(0,0,0,0.12)',
    hoverBg: 'rgba(0,0,0,0.06)', overlayBg: 'rgba(0,0,0,0.45)',
  },
};
